### ISSUE TITLE
Why is `Prim` a separate effect?

### ISSUE THREAD

**Issue by re-xyr** [arybczak/effectful#45]
To me, `Prim` just seems like `IOE` without unlifting support; and I cannot think of any scenario where I want to express precisely "I only want `liftIO` but not `withRunInIO`". What about merging the support of `PrimMonad` class into `IOE` functionality and removing `Prim`?

**Comment by arybczak** [comment]
While `primitive` is as powerful as `liftIO`, it's harder to use it like that since you need access to the `IO` constructor. So having `Prim`, but not `IOE` could be for signifying that only "reasonable" operations are used such as the ones from `primitive` or `vector`.

IMO no choice is without downsides here :thinking:

**Comment by arybczak** [comment]
`Prim` will be kept separate, the ability to use things from `primitive` without pulling in the whole `IO` is quite useful.
